Meet after lunch la...
Wth ok i chilling out with family at macs they can sign
Haha I got two exams on one day times two sia... but means finish fast!
Submit hardcopy.
Haha I tmr confirm with u again.
Dear ah.. dun wake up so early. I set my alarm clock. Love usweety.!!
If u can, wait. Or change 2 a dr who comes 2moro at 5 or 6.
Hi, ulu pandan needs more blue claim forms. Thanks.
Lols imma no sj. Got no date